import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import styled, { createGlobalStyle } from "styled-components";
import SpotifyLoginLogo from "/Users/them/Documents/neuefische/capstone/cap/cap2/capi/capstone_project/public/assets/images/login/spotify/icon4@2x.png";
import SefoBackground from "/Users/them/Documents/neuefische/capstone/cap/cap2/capi/capstone_project/public/assets/images/login/background/sefo-bg.jpeg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <StyledBody>
        <main className={`${styles.main} ${inter.className}`}>
          <Title>
            <h1>Share youre lovely music with Music</h1>
          </Title>
          <StyledButton>
            <Link href="/components/feed">
              <ButtonText>Login with Spotify</ButtonText>
            </Link>
            <SpotifyLogo>
              <Image
                src={SpotifyLoginLogo}
                width={45}
                height={45}
                alt="Spotify"
              />
            </SpotifyLogo>
          </StyledButton>
        </main>
      </StyledBody>
    </>
  );
}

const GlobalStyle = createGlobalStyle`
body {
  font-family: "CircularSpotifyTxT-Light";
}`;

const StyledBody = styled.body`
  background-image: url(${SefoBackground.src});
  background-size: cover;
  background-position: right;
`;

const Title = styled.div`
  color: rgba(30, 215, 96);
  margin-top: 20px;
`;
const StyledButton = styled.button`
  background-color: rgba(30, 215, 96);
  border: none;
  border-radius: 32px;
  color: white;
  display: flex;
  align-items: center;
  width: 260px;
  height: 50px;
  margin-bottom: 80px;
`;

const ButtonText = styled.span`
  font-size: 19px;
  margin-left: 40px;
  color: #fff;
`;

const SpotifyLogo = styled.image`
  margin-right: 10px;
`;
